
--- 

debug: true

can1:
  baud_rate: 1000000

can2:
  baud_rate: 500000

radar:
  debug: true
  can_line: "can2"

steering: 
  debug: true
  can_line: "can1"
  motor_id: 104
  mode: 3


vehicle:
  debug: true
  can_line: "can1"
