
--- 

debug: false

can1:
  baud_rate: 1000000 

can2:
  baud_rate: 1000000

radar:
  debug: false
  can_line: "can2"

steering: 
  debug: false
  can_line: "can1"
  motor_id: 25
  mode: 3


vehicle:
  debug: false
  can_line: "can2"
